// <auto-generated />
using Animal_Shelter_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animal_Shelter_Api.Migrations
{
    [DbContext(typeof(Animal_Shelter_ApiContext))]
    [Migration("20230818173256_UpdateFuturePetClass")]
    partial class UpdateFuturePetClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Animal_Shelter_Api.Models.FuturePet", b =>
                {
                    b.Property<int>("FuturePetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("CoatColor")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("FuturePetId");

                    b.ToTable("FuturePets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FuturePet");
                });

            modelBuilder.Entity("Animal_Shelter_Api.Models.Cat", b =>
                {
                    b.HasBaseType("Animal_Shelter_Api.Models.FuturePet");

                    b.Property<bool>("FivPositive")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue("Cat");

                    b.HasData(
                        new
                        {
                            FuturePetId = 1,
                            Age = 1,
                            Breed = "Siamese",
                            CoatColor = "White",
                            Name = "Coco",
                            FivPositive = false
                        },
                        new
                        {
                            FuturePetId = 2,
                            Age = 3,
                            Breed = "Ragamuffin",
                            CoatColor = "Chestnut",
                            Name = "Tuffy",
                            FivPositive = true
                        },
                        new
                        {
                            FuturePetId = 3,
                            Age = 3,
                            Breed = "Maine Coon",
                            CoatColor = "Grey",
                            Name = "Fernando",
                            FivPositive = false
                        });
                });

            modelBuilder.Entity("Animal_Shelter_Api.Models.Dog", b =>
                {
                    b.HasBaseType("Animal_Shelter_Api.Models.FuturePet");

                    b.Property<int>("DogSize")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Dog");

                    b.HasData(
                        new
                        {
                            FuturePetId = 4,
                            Age = 4,
                            Breed = "Corgi",
                            CoatColor = "Sable",
                            Name = "Bing",
                            DogSize = 0
                        },
                        new
                        {
                            FuturePetId = 5,
                            Age = 3,
                            Breed = "Pug",
                            CoatColor = "Brindle",
                            Name = "Mushroom",
                            DogSize = 0
                        },
                        new
                        {
                            FuturePetId = 6,
                            Age = 1,
                            Breed = "Great Pyrenees",
                            CoatColor = "Red",
                            Name = "Felix",
                            DogSize = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
