// <auto-generated />
using Animal_Shelter_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animal_Shelter_Api.Migrations
{
    [DbContext(typeof(Animal_Shelter_ApiContext))]
    [Migration("20230818163436_UpdatePrimaryKey")]
    partial class UpdatePrimaryKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Animal_Shelter_Api.Models.FuturePet", b =>
                {
                    b.Property<int>("FuturePetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("FuturePetId");

                    b.ToTable("FuturePets");
                });
#pragma warning restore 612, 618
        }
    }
}
